'use client';

export const ReportDisclaimer = () => {
  return (
    <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-6">
      <h3 className="font-semibold text-gray-900 mb-2">Important Disclaimer</h3>
      <p className="text-sm text-gray-700 mb-2">
        This assessment is generated by AI and should NOT be considered:
      </p>
      <ul className="text-sm text-gray-700 space-y-1 ml-4">
        <li>• A substitute for professional legal advice</li>
        <li>• A guarantee of case outcome</li>
        <li>• A replacement for consulting with a qualified lawyer</li>
        <li>• A basis for legal decisions without professional review</li>
      </ul>
      <p className="text-sm text-gray-700 mt-2">
        Always consult with a qualified legal professional before proceeding with any legal matter.
      </p>
    </div>
  );
};
